import {
  Injectable,
  NotFoundException,
  BadRequestException,
  Inject,
  forwardRef,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, In } from 'typeorm';
import { PayrollRun, PayrollStatus } from './entities/payroll-run.entity';
import { PayrollEntry, PayrollEntryStatus } from './entities/payroll-entry.entity';
import { EmployeesService } from '../employees/employees.service';
import { AttendanceService } from '../attendance/attendance.service';
import { Employee, EmployeeType } from '../employees/entities/employee.entity';
import { AttendanceStatus } from '../attendance/entities/attendance.entity';
import { User } from '../users/entities/user.entity';
import { PayrollIntegrationService } from '../expenses/payroll-integration.service';

// Default overtime multiplier
const DEFAULT_OVERTIME_MULTIPLIER = 1.5;
const SALARY_DAYS = 30; // Fixed divisor as per user requirement

// Helper function to calculate Mondays in a month
function getMondaysInMonth(year: number, month: number): number {
  const daysInMonth = new Date(year, month, 0).getDate();
  let mondays = 0;
  for (let d = 1; d <= daysInMonth; d++) {
    if (new Date(year, month - 1, d).getDay() === 1) {
      mondays++;
    }
  }
  return mondays;
}

// Helper to get total days in month
function getDaysInMonth(year: number, month: number): number {
  return new Date(year, month, 0).getDate();
}

@Injectable()
export class PayrollService {
  constructor(
    @InjectRepository(PayrollRun)
    private payrollRunRepository: Repository<PayrollRun>,
    @InjectRepository(PayrollEntry)
    private payrollEntryRepository: Repository<PayrollEntry>,
    @InjectRepository(User)
    private userRepository: Repository<User>,
    private employeesService: EmployeesService,
    private attendanceService: AttendanceService,
    @Inject(forwardRef(() => PayrollIntegrationService))
    private payrollIntegrationService: PayrollIntegrationService
  ) {}

  async runPayroll(
    year: number,
    month: number,
    userId: string,
    isAutoGenerated = false,
    overtimeMultiplier = DEFAULT_OVERTIME_MULTIPLIER,
    overwrite = false
  ): Promise<PayrollRun> {
    // Check if payroll already exists for this month
    const runForMonth = new Date(year, month - 1, 1);
    const existingRun = await this.payrollRunRepository.findOne({
      where: { runForMonth },
    });

    if (existingRun && existingRun.status !== PayrollStatus.DRAFT && !overwrite) {
      throw new BadRequestException(
        `Payroll already processed for ${year}-${month}. Use overwrite=true to re-run.`
      );
    }

    // If overwrite is true and there's an existing run, delete it first
    if (existingRun && overwrite) {
      await this.payrollEntryRepository.delete({ payrollRunId: existingRun.id });
      await this.payrollRunRepository.delete({ id: existingRun.id });
    }

    // Use provided multiplier or default
    const multiplier = overtimeMultiplier || DEFAULT_OVERTIME_MULTIPLIER;

    // Get all active employees
    const employees = await this.employeesService.getActiveEmployees();

    // Create payroll run
    const payrollRun = this.payrollRunRepository.create({
      runForMonth,
      runDate: new Date(),
      status: PayrollStatus.PROCESSED,
      isAutoGenerated,
      generatedBy: userId,
    });

    // Create new payroll run
    const savedRun = await this.payrollRunRepository.save(payrollRun);

    // Process each employee
    const entries: PayrollEntry[] = [];

    // Process each employee - overtime is now calculated based on attendance, not end of month
    for (const employee of employees) {
      const entry = await this.calculatePayrollEntry(
        savedRun.id,
        employee,
        year,
        month,
        false, // isEndOfMonth - no longer used, calculated based on attendance
        multiplier
      );
      entries.push(entry);
    }

    // Save all entries
    await this.payrollEntryRepository.save(entries);

    // Apply employee advance deductions to each entry
    const monthStr = `${year}-${String(month).padStart(2, '0')}`;
    for (const entry of entries) {
      const monthAdvanceTotal = await this.payrollIntegrationService.computeMonthAdvanceTotal(
        entry.employeeId,
        monthStr
      );

      if (monthAdvanceTotal > 0) {
        const carryForwardIn = await this.payrollIntegrationService.getCarryForwardIn(
          entry.employeeId,
          monthStr
        );

        const totalDeduction = monthAdvanceTotal + carryForwardIn;
        const grossSalary = Number(entry.grossSalary);

        entry.advancesDeducted = totalDeduction;
        entry.carryForwardIn = carryForwardIn;

        if (totalDeduction > grossSalary) {
          entry.carryForwardOut = totalDeduction - grossSalary;
          entry.deductions = Number(entry.halfDaysDeduction) + totalDeduction;
          entry.netSalary = 0;
        } else {
          entry.carryForwardOut = 0;
          entry.deductions = Number(entry.halfDaysDeduction) + totalDeduction;
          entry.netSalary = grossSalary - entry.deductions;
          if (entry.netSalary < 0) entry.netSalary = 0;
        }

        await this.payrollEntryRepository.save(entry);
      }
    }

    return this.findPayrollRun(savedRun.id);
  }

  private async calculatePayrollEntry(
    payrollRunId: string,
    employee: Employee,
    year: number,
    month: number,
    isEndOfMonth: boolean,
    overtimeMultiplier: number
  ): Promise<PayrollEntry> {
    // For permanent employees, calculate based on attendance
    if (employee.employeeType === EmployeeType.PERMANENT) {
      return this.calculatePermanentEmployeePayroll(
        payrollRunId,
        employee,
        year,
        month,
        isEndOfMonth,
        overtimeMultiplier
      );
    }

    // For occasional employees, sum up visits
    if (employee.employeeType === EmployeeType.OCCASIONAL) {
      return this.calculateOccasionalEmployeePayroll(payrollRunId, employee, year, month);
    }

    // For picker employees, sum up picker work
    if (employee.employeeType === EmployeeType.PICKER) {
      return this.calculatePickerEmployeePayroll(payrollRunId, employee, year, month);
    }

    throw new BadRequestException(`Unknown employee type: ${employee.employeeType}`);
  }

  private async calculatePermanentEmployeePayroll(
    payrollRunId: string,
    employee: Employee,
    year: number,
    month: number,
    _isEndOfMonth: boolean,
    overtimeMultiplier: number
  ): Promise<PayrollEntry> {
    const attendance = await this.attendanceService.getEmployeeAttendanceForMonth(
      employee.id,
      year,
      month
    );

    const monthlySalary = Number(employee.monthlySalary) || 0;

    // Fixed: Use 30 days as divisor for deduction calculation
    const dailyRate = monthlySalary / SALARY_DAYS;

    // Get actual days in the month and Mondays
    const totalDaysInMonth = getDaysInMonth(year, month);
    const mondaysInMonth = getMondaysInMonth(year, month);

    // Required shifts = Total days - Mondays (Mondays are holidays)
    // Employee works required shifts to get full salary
    const requiredShifts = totalDaysInMonth - mondaysInMonth;

    // Count ALL attendance records as shifts worked
    // PRESENT, WORKING (Monday holiday worked), and HOLIDAY (company holiday) count as full shift (1.0)
    // HALF_DAY counts as half shift (0.5)
    const fullDayShifts = attendance.filter(
      a =>
        a.status === AttendanceStatus.PRESENT ||
        a.status === AttendanceStatus.WORKING ||
        a.status === AttendanceStatus.HOLIDAY
    ).length;
    const halfDayShifts = attendance.filter(a => a.status === AttendanceStatus.HALF_DAY).length;

    // Total shifts worked (full + half)
    const effectiveWorkingShifts = fullDayShifts + halfDayShifts * 0.5;

    // Calculate base salary proportionally based on days worked
    // If employee works 0 days, salary is 0
    // If employee works less than required days, salary is proportional
    // If employee works required days or more, salary is full monthly salary
    let baseSalary: number;
    let overtimeAmount = 0;
    let overtimeShifts = 0;

    if (effectiveWorkingShifts === 0) {
      // No days worked = no salary
      baseSalary = 0;
    } else if (effectiveWorkingShifts < requiredShifts) {
      // Less than required days = proportional salary
      baseSalary = (effectiveWorkingShifts / requiredShifts) * monthlySalary;
    } else {
      // Required days or more = full salary
      baseSalary = monthlySalary;
      // Overtime: only paid for extra shifts beyond required
      overtimeShifts = effectiveWorkingShifts - requiredShifts;
      overtimeAmount = overtimeShifts * dailyRate * overtimeMultiplier;
    }

    // Half day deduction: each half day deducts 0.5 day's pay
    const halfDayDeduction = halfDayShifts * (dailyRate * 0.5);
    const totalDeductions = halfDayDeduction;

    // Calculate salaries
    const grossSalary = baseSalary + overtimeAmount;
    const netSalary = grossSalary - totalDeductions;

    return this.payrollEntryRepository.create({
      payrollRunId,
      employeeId: employee.id,
      workingDays: effectiveWorkingShifts,
      dailyRate,
      baseSalary,
      overtimeAmount,
      overtimeDays: overtimeShifts,
      overtimeMultiplier: overtimeShifts > 0 ? overtimeMultiplier : 0,
      halfDaysDeduction: halfDayDeduction,
      halfDayCount: halfDayShifts,
      grossSalary,
      deductions: totalDeductions,
      netSalary,
      status: PayrollEntryStatus.PENDING,
    });
  }

  private async calculateOccasionalEmployeePayroll(
    payrollRunId: string,
    employee: Employee,
    _year: number,
    _month: number
  ): Promise<PayrollEntry> {
    // For now, we'll return 0 - actual visit calculation would need EmployeeVisit entity
    return this.payrollEntryRepository.create({
      payrollRunId,
      employeeId: employee.id,
      workingDays: 0,
      dailyRate: 0,
      baseSalary: 0,
      overtimeAmount: 0,
      overtimeDays: 0,
      overtimeMultiplier: 0,
      halfDaysDeduction: 0,
      halfDayCount: 0,
      grossSalary: 0,
      deductions: 0,
      netSalary: 0,
      status: PayrollEntryStatus.PENDING,
    });
  }

  private async calculatePickerEmployeePayroll(
    payrollRunId: string,
    employee: Employee,
    _year: number,
    _month: number
  ): Promise<PayrollEntry> {
    // For now, we'll return 0 - actual picker work calculation would need PickerWork entity
    return this.payrollEntryRepository.create({
      payrollRunId,
      employeeId: employee.id,
      workingDays: 0,
      dailyRate: 0,
      baseSalary: 0,
      overtimeAmount: 0,
      overtimeDays: 0,
      overtimeMultiplier: 0,
      halfDaysDeduction: 0,
      halfDayCount: 0,
      grossSalary: 0,
      deductions: 0,
      netSalary: 0,
      status: PayrollEntryStatus.PENDING,
    });
  }

  async findPayrollRun(id: string): Promise<PayrollRun> {
    const run = await this.payrollRunRepository.findOne({
      where: { id },
      relations: ['entries', 'entries.employee'],
    });

    if (!run) {
      throw new NotFoundException(`Payroll run with ID ${id} not found`);
    }

    return run;
  }

  async getPayrollByMonth(year: number, month: number): Promise<PayrollRun | null> {
    const runForMonth = new Date(year, month - 1, 1);

    return this.payrollRunRepository.findOne({
      where: { runForMonth },
      relations: ['entries', 'entries.employee'],
    });
  }

  async getAllPayrollRuns(): Promise<PayrollRun[]> {
    const runs = await this.payrollRunRepository.find({
      relations: ['entries', 'entries.employee'],
      order: { runForMonth: 'DESC' },
    });

    // Get all unique user IDs
    const userIds = [...new Set(runs.map(run => run.generatedBy).filter(Boolean))] as string[];

    // Fetch users if we have any
    let users: User[] = [];
    if (userIds.length > 0) {
      users = await this.userRepository.find({ where: { id: In(userIds) } });
    }

    // Map user names to runs
    const userMap = new Map(users.map(u => [u.id, `${u.firstName} ${u.lastName || ''}`.trim()]));

    return runs.map(run => ({
      ...run,
      processedByName: run.generatedBy ? userMap.get(run.generatedBy) || 'Unknown' : 'N/A',
    }));
  }

  async lockPayroll(id: string): Promise<PayrollRun> {
    const run = await this.findPayrollRun(id);
    run.status = PayrollStatus.LOCKED;
    return this.payrollRunRepository.save(run);
  }

  async unlockPayroll(id: string): Promise<PayrollRun> {
    const run = await this.findPayrollRun(id);
    run.status = PayrollStatus.PROCESSED;
    return this.payrollRunRepository.save(run);
  }

  async updatePayrollEntry(id: string, data: Partial<PayrollEntry>): Promise<PayrollEntry> {
    const entry = await this.payrollEntryRepository.findOne({ where: { id } });

    if (!entry) {
      throw new NotFoundException(`Payroll entry with ID ${id} not found`);
    }

    // Check if payroll is locked
    const run = await this.payrollRunRepository.findOne({
      where: { id: entry.payrollRunId },
    });

    if (run?.status === PayrollStatus.LOCKED) {
      throw new BadRequestException('Cannot edit locked payroll');
    }

    Object.assign(entry, data);
    return this.payrollEntryRepository.save(entry);
  }

  async getPayrollEntry(id: string): Promise<PayrollEntry> {
    const entry = await this.payrollEntryRepository.findOne({
      where: { id },
      relations: ['employee'],
    });

    if (!entry) {
      throw new NotFoundException(`Payroll entry with ID ${id} not found`);
    }

    return entry;
  }

  async getPayrollEntryByEmployeeAndMonth(
    employeeId: string,
    year: number,
    month: number
  ): Promise<PayrollEntry | null> {
    // Find the payroll run for this month/year using runForMonth
    const startOfMonth = new Date(year, month - 1, 1);
    const endOfMonth = new Date(year, month, 0);

    const payrollRun = await this.payrollRunRepository
      .createQueryBuilder('run')
      .where('run.runForMonth >= :startOfMonth', { startOfMonth })
      .andWhere('run.runForMonth <= :endOfMonth', { endOfMonth })
      .getOne();

    if (!payrollRun) {
      return null;
    }

    // Find the entry for this employee in that run
    const entry = await this.payrollEntryRepository.findOne({
      where: {
        payrollRun: { id: payrollRun.id },
        employee: { id: employeeId },
      },
      relations: ['employee', 'payrollRun'],
    });

    return entry;
  }

  // Helper method to get active employees for preview
  async getActiveEmployeesForPreview() {
    return this.employeesService.getActiveEmployees();
  }

  // Helper method to get monthly attendance for preview
  async getMonthlyAttendanceForPreview(year: number, month: number) {
    return this.attendanceService.getMonthlyAttendance(year, month);
  }

  async getPayrollSummary(
    year: number,
    month: number
  ): Promise<{
    totalPayroll: number;
    employeeCount: number;
    byType: Record<string, { count: number; amount: number }>;
  }> {
    const run = await this.getPayrollByMonth(year, month);

    if (!run) {
      return {
        totalPayroll: 0,
        employeeCount: 0,
        byType: {},
      };
    }

    const byType: Record<string, { count: number; amount: number }> = {};
    let totalPayroll = 0;

    for (const entry of run.entries) {
      const employee = entry.employee as Employee;
      const type = employee.employeeType;

      if (!byType[type]) {
        byType[type] = { count: 0, amount: 0 };
      }

      byType[type].count++;
      byType[type].amount += Number(entry.netSalary);
      totalPayroll += Number(entry.netSalary);
    }

    return {
      totalPayroll,
      employeeCount: run.entries.length,
      byType,
    };
  }
}
