import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { PayrollRun, PayrollStatus } from './entities/payroll-run.entity';
import { PayrollEntry, PayrollEntryStatus } from './entities/payroll-entry.entity';
import { EmployeesService } from '../employees/employees.service';
import { AttendanceService } from '../attendance/attendance.service';
import { Employee, EmployeeType } from '../employees/entities/employee.entity';
import { AttendanceStatus } from '../attendance/entities/attendance.entity';

// Default overtime multiplier
const DEFAULT_OVERTIME_MULTIPLIER = 1.5;

@Injectable()
export class PayrollService {
  constructor(
    @InjectRepository(PayrollRun)
    private payrollRunRepository: Repository<PayrollRun>,
    @InjectRepository(PayrollEntry)
    private payrollEntryRepository: Repository<PayrollEntry>,
    private employeesService: EmployeesService,
    private attendanceService: AttendanceService
  ) {}

  async runPayroll(
    year: number,
    month: number,
    userId: string,
    isAutoGenerated = false,
    overtimeMultiplier = DEFAULT_OVERTIME_MULTIPLIER
  ): Promise<PayrollRun> {
    // Check if payroll already exists for this month
    const runForMonth = new Date(year, month - 1, 1);
    const existingRun = await this.payrollRunRepository.findOne({
      where: { runForMonth },
    });

    if (existingRun && existingRun.status !== PayrollStatus.DRAFT) {
      throw new BadRequestException(`Payroll already processed for ${year}-${month}`);
    }

    // Check if it's end of month (for overtime calculation)
    const today = new Date();
    const isEndOfMonth = today.getMonth() + 1 === month && today.getDate() >= 28;

    // Use provided multiplier or default
    const multiplier = overtimeMultiplier || DEFAULT_OVERTIME_MULTIPLIER;

    // Get all active employees
    const employees = await this.employeesService.getActiveEmployees();

    // Create payroll run
    const payrollRun = this.payrollRunRepository.create({
      runForMonth,
      runDate: new Date(),
      status: PayrollStatus.PROCESSED,
      isAutoGenerated,
      generatedBy: userId,
    });

    const savedRun = await this.payrollRunRepository.save(payrollRun);

    // Process each employee
    const entries: PayrollEntry[] = [];

    for (const employee of employees) {
      const entry = await this.calculatePayrollEntry(
        savedRun.id,
        employee,
        year,
        month,
        isEndOfMonth,
        multiplier
      );
      entries.push(entry);
    }

    // Save all entries
    await this.payrollEntryRepository.save(entries);

    return this.findPayrollRun(savedRun.id);
  }

  private async calculatePayrollEntry(
    payrollRunId: string,
    employee: Employee,
    year: number,
    month: number,
    isEndOfMonth: boolean,
    overtimeMultiplier: number
  ): Promise<PayrollEntry> {
    // For permanent employees, calculate based on attendance
    if (employee.employeeType === EmployeeType.PERMANENT) {
      return this.calculatePermanentEmployeePayroll(
        payrollRunId,
        employee,
        year,
        month,
        isEndOfMonth,
        overtimeMultiplier
      );
    }

    // For occasional employees, sum up visits
    if (employee.employeeType === EmployeeType.OCCASIONAL) {
      return this.calculateOccasionalEmployeePayroll(payrollRunId, employee, year, month);
    }

    // For picker employees, sum up picker work
    if (employee.employeeType === EmployeeType.PICKER) {
      return this.calculatePickerEmployeePayroll(payrollRunId, employee, year, month);
    }

    throw new BadRequestException(`Unknown employee type: ${employee.employeeType}`);
  }

  private async calculatePermanentEmployeePayroll(
    payrollRunId: string,
    employee: Employee,
    year: number,
    month: number,
    isEndOfMonth: boolean,
    overtimeMultiplier: number
  ): Promise<PayrollEntry> {
    const attendance = await this.attendanceService.getEmployeeAttendanceForMonth(
      employee.id,
      year,
      month
    );

    const monthlySalary = Number(employee.monthlySalary) || 0;
    const dailyRate = monthlySalary / 30;

    // Count different attendance types
    const presentDays = attendance.filter(a => a.status === AttendanceStatus.PRESENT).length;
    const halfDays = attendance.filter(a => a.status === AttendanceStatus.HALF_DAY).length;
    const workedMonday = attendance.filter(a => a.status === AttendanceStatus.WORKED_MONDAY).length;

    // Calculate work balance (Monday worked = extra day)
    // For simplicity, we'll consider each worked Monday as +1 day
    const effectiveWorkingDays = presentDays + workedMonday + halfDays * 0.5;

    // Calculate overtime (only at end of month)
    let overtimeDays = 0;
    let overtimeAmount = 0;

    if (isEndOfMonth) {
      // Overtime = days worked beyond 25 days (standard working days in month excluding Mondays)
      const standardWorkingDays = 25; // 30 days - ~4 Mondays
      overtimeDays = Math.max(0, effectiveWorkingDays - standardWorkingDays);
      overtimeAmount = overtimeDays * dailyRate * overtimeMultiplier;
    }

    // Half day deduction
    const halfDayDeduction = halfDays * (dailyRate * 0.5);

    // Calculate salaries
    const baseSalary = effectiveWorkingDays * dailyRate;
    const grossSalary = baseSalary + overtimeAmount;
    const netSalary = grossSalary - halfDayDeduction;

    return this.payrollEntryRepository.create({
      payrollRunId,
      employeeId: employee.id,
      workingDays: effectiveWorkingDays,
      dailyRate,
      baseSalary,
      overtimeAmount,
      overtimeDays,
      overtimeMultiplier: isEndOfMonth ? overtimeMultiplier : 0,
      halfDaysDeduction: halfDayDeduction,
      halfDayCount: halfDays,
      grossSalary,
      deductions: 0,
      netSalary,
      status: PayrollEntryStatus.PENDING,
    });
  }

  private async calculateOccasionalEmployeePayroll(
    payrollRunId: string,
    employee: Employee,
    _year: number,
    _month: number
  ): Promise<PayrollEntry> {
    // For now, we'll return 0 - actual visit calculation would need EmployeeVisit entity
    return this.payrollEntryRepository.create({
      payrollRunId,
      employeeId: employee.id,
      workingDays: 0,
      dailyRate: 0,
      baseSalary: 0,
      overtimeAmount: 0,
      overtimeDays: 0,
      overtimeMultiplier: 0,
      halfDaysDeduction: 0,
      halfDayCount: 0,
      grossSalary: 0,
      deductions: 0,
      netSalary: 0,
      status: PayrollEntryStatus.PENDING,
    });
  }

  private async calculatePickerEmployeePayroll(
    payrollRunId: string,
    employee: Employee,
    _year: number,
    _month: number
  ): Promise<PayrollEntry> {
    // For now, we'll return 0 - actual picker work calculation would need PickerWork entity
    return this.payrollEntryRepository.create({
      payrollRunId,
      employeeId: employee.id,
      workingDays: 0,
      dailyRate: 0,
      baseSalary: 0,
      overtimeAmount: 0,
      overtimeDays: 0,
      overtimeMultiplier: 0,
      halfDaysDeduction: 0,
      halfDayCount: 0,
      grossSalary: 0,
      deductions: 0,
      netSalary: 0,
      status: PayrollEntryStatus.PENDING,
    });
  }

  async findPayrollRun(id: string): Promise<PayrollRun> {
    const run = await this.payrollRunRepository.findOne({
      where: { id },
      relations: ['entries', 'entries.employee'],
    });

    if (!run) {
      throw new NotFoundException(`Payroll run with ID ${id} not found`);
    }

    return run;
  }

  async getPayrollByMonth(year: number, month: number): Promise<PayrollRun | null> {
    const runForMonth = new Date(year, month - 1, 1);

    return this.payrollRunRepository.findOne({
      where: { runForMonth },
      relations: ['entries', 'entries.employee'],
    });
  }

  async getAllPayrollRuns(): Promise<PayrollRun[]> {
    return this.payrollRunRepository.find({
      order: { runForMonth: 'DESC' },
    });
  }

  async lockPayroll(id: string): Promise<PayrollRun> {
    const run = await this.findPayrollRun(id);
    run.status = PayrollStatus.LOCKED;
    return this.payrollRunRepository.save(run);
  }

  async unlockPayroll(id: string): Promise<PayrollRun> {
    const run = await this.findPayrollRun(id);
    run.status = PayrollStatus.PROCESSED;
    return this.payrollRunRepository.save(run);
  }

  async updatePayrollEntry(id: string, data: Partial<PayrollEntry>): Promise<PayrollEntry> {
    const entry = await this.payrollEntryRepository.findOne({ where: { id } });

    if (!entry) {
      throw new NotFoundException(`Payroll entry with ID ${id} not found`);
    }

    // Check if payroll is locked
    const run = await this.payrollRunRepository.findOne({
      where: { id: entry.payrollRunId },
    });

    if (run?.status === PayrollStatus.LOCKED) {
      throw new BadRequestException('Cannot edit locked payroll');
    }

    Object.assign(entry, data);
    return this.payrollEntryRepository.save(entry);
  }

  async getPayrollEntry(id: string): Promise<PayrollEntry> {
    const entry = await this.payrollEntryRepository.findOne({
      where: { id },
      relations: ['employee'],
    });

    if (!entry) {
      throw new NotFoundException(`Payroll entry with ID ${id} not found`);
    }

    return entry;
  }

  async getPayrollSummary(
    year: number,
    month: number
  ): Promise<{
    totalPayroll: number;
    employeeCount: number;
    byType: Record<string, { count: number; amount: number }>;
  }> {
    const run = await this.getPayrollByMonth(year, month);

    if (!run) {
      return {
        totalPayroll: 0,
        employeeCount: 0,
        byType: {},
      };
    }

    const byType: Record<string, { count: number; amount: number }> = {};
    let totalPayroll = 0;

    for (const entry of run.entries) {
      const employee = entry.employee as Employee;
      const type = employee.employeeType;

      if (!byType[type]) {
        byType[type] = { count: 0, amount: 0 };
      }

      byType[type].count++;
      byType[type].amount += Number(entry.netSalary);
      totalPayroll += Number(entry.netSalary);
    }

    return {
      totalPayroll,
      employeeCount: run.entries.length,
      byType,
    };
  }
}
