export enum WastageCategory {
  CUT_PIECE = 'CUT_PIECE',
  POWER_CUT_CHANGE_OVER = 'POWER_CUT_CHANGE_OVER',
  UNGRINDABLE_SCREEN_CHANGE = 'UNGRINDABLE_SCREEN_CHANGE',
  MISHANDLING = 'MISHANDLING',
}
