import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  ManyToOne,
  JoinColumn,
  OneToMany,
} from 'typeorm';
import { PayrollEntry } from './payroll-entry.entity';

export enum PayrollStatus {
  DRAFT = 'DRAFT',
  PROCESSED = 'PROCESSED',
  LOCKED = 'LOCKED',
}

@Entity('payroll_run')
export class PayrollRun {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'run_for_month', type: 'date' })
  runForMonth: Date;

  @Column({ name: 'run_date', type: 'date' })
  runDate: Date;

  @Column({
    type: 'enum',
    enum: PayrollStatus,
    default: PayrollStatus.DRAFT,
  })
  status: PayrollStatus;

  @Column({ name: 'is_auto_generated', default: false })
  isAutoGenerated: boolean;

  @Column({ name: 'generated_by', nullable: true })
  generatedBy: string;

  @ManyToOne(() => PayrollRun)
  @JoinColumn({ name: 'generated_by' })
  generator: PayrollRun;

  @OneToMany(() => PayrollEntry, entry => entry.payrollRun, { cascade: true })
  entries: PayrollEntry[];

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;
}
