# Deploy to Production
name: Deploy - Production

on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render Production
        uses: johnbeynon/render-deploy-action@v0.0.1
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID_PROD }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          environment-id: ${{ secrets.RENDER_ENVIRONMENT_ID_PROD }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET_PROD }}
