# Deploy to Beta
name: Deploy - Beta

on:
  push:
    branches: [dev]

jobs:
  deploy-beta:
    runs-on: ubuntu-latest
    environment: beta

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render Beta
        uses: johnbeynon/render-deploy-action@v0.0.1
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID_BETA }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          environment-id: ${{ secrets.RENDER_ENVIRONMENT_ID_BETA }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_BETA }}
          JWT_SECRET: ${{ secrets.JWT_SECRET_BETA }}
